REM
INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into MS_ASANFINANCE_EMP_ACTIVE (ID, CONTRACT_BEGINDATE, CONTRACT_ENDDATE, CONTRACT_INSERTDATE,
                                       CONTRACT_NEXTENDDATE, CONTRACT_SIGN_DATE, CREATE_DATE, EMPLOYEE_NAME,
                                       EMPLOYEE_PATRONYMIC, EMPLOYEE_PHONE, EMPLOYEE_SURNAME, EMPLOYER_LEGAL_ADDRESS,
                                       EMPLOYER_NAME, EMPLOYER_PHONE, EMPLOYER_VOEN, EMPLOYER_WORKER_COUNT,
                                       CONTRACT_NUMBER, PERIODTYPE_DESCRIPTION, PERIODTYPE_LABEL, PIN_CODE, POSITION,
                                       POSITION_LABOUR_CONTRACT, REQUEST_ID, SALARY, SSN, STATUS_DESCRIPTION,
                                       STATUS_LABEL, WCT_DESCRIPTION, WCT_LABEL, WORK_PLACE, WPT_DESCRIPTION, WPT_LABEL,
                                       EMPLOYER_PROPERTY_TYPE_LAYER, EMPLOYER_PROPERTY_TYPE_DESC)
values ('BEFA7CBB63500218E053C0A862352605', to_date('20-JUN-17', 'DD-MON-RR'), to_date('17-MAY-22', 'DD-MON-RR'),
        to_date('02-JUL-21', 'DD-MON-RR'), to_date('17-MAY-22', 'DD-MON-RR'), to_date('02-JUL-21', 'DD-MON-RR'),
        to_timestamp('29-OCT-21 06.57.02.000000000 PM', 'DD-MON-RR HH.MI.SSXFF AM'), 'VASIF', 'ARIF OGLU', null,
        'SIXALLYEV', 'AZ1005, AZERBAYCAN, BAKI SeHeRi, NeSiMi RAYONU, NiZAMi, EV 67',
        '"AZERBAYCAN BEYNELXALQ BANKI" AÇIQ SEHMDAR CEMIYYETI', '4988536', '9900001881', 2724, '5BDBZBM000411',
        'Müddetli', '1', '2GMKLD0', 'qrup rehberi', 'qrup' ','9ed718ca-154d-4efe-b64b-2c93b0c6eaf8',6515,'2112199101531','Qüvvededir','1','Vaxtamuzd','2','Proqram departamenti -> Bank sistemlErinin inkisafi','esas','1','1','Dövlet mülkiyyeti');